"""Add stripe fields to user model

Revision ID: 2c3914f9c5e9
Revises: f8d9f0857c64
Create Date: 2025-09-28 14:44:19.129753

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2c3914f9c5e9"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "f8d9f0857c64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "stripe_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column("subscription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "subscription_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "user", sa.Column("plan_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("subscription_ends_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_user_stripe_customer_id"), "user", ["stripe_customer_id"], unique=True
    )
    op.create_unique_constraint(None, "user", ["subscription_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_index(op.f("ix_user_stripe_customer_id"), table_name="user")
    op.drop_column("user", "subscription_ends_at")
    op.drop_column("user", "plan_id")
    op.drop_column("user", "subscription_status")
    op.drop_column("user", "subscription_id")
    op.drop_column("user", "stripe_customer_id")
    # ### end Alembic commands ###
