"""add keyframe_indices to agentrun

Revision ID: 470bee1dc486
Revises: 5ff4243f6cce
Create Date: 2025-09-28 20:43:34.853346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "470bee1dc486"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "5ff4243f6cce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agentrun",
        sa.Column(
            "keyframe_indices", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agentrun", "keyframe_indices")
    # ### end Alembic commands ###
