"""Add report_path to AgentRun

Revision ID: 5ff4243f6cce
Revises: c110a9535ac2
Create Date: 2025-09-28 18:11:57.992294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "5ff4243f6cce"
down_revision: Union[str, Sequence[str], None] = "c110a9535ac2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agentrun",
        sa.Column("report_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agentrun", "report_path")
    # ### end Alembic commands ###
