"""Initial migration

Revision ID: cb1461dc0cb2
Revises:
Create Date: 2025-09-28 01:09:21.674258

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cb1461dc0cb2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
