# Blueprint for a Stage 2 "Reasoning" Fine-Tune

# --- MODEL, DATA & OUTPUT ---
# CRITICAL: We start from our Stage 1 model, not the base model.
base_model: "forge/checkpoints/churninator-smollm-1.7b-grounded-v1/final"
data_file: "stage2_reasoning.jsonl"
output_dir: "churninator-smollm-1.7b-reasoning-v1"

# --- OVERRIDES ---
learning_rate: 5.0e-5
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
