# Blueprint for a Stage 1 "Grounding" Fine-Tune

# --- DATA & OUTPUT ---
data_file: "stage1_grounding.jsonl"
output_dir: "churninator-smollm-1.7b-grounded-v1"

# --- OVERRIDES ---
lora_r: 32
lora_alpha: 64
lora_dropout: 0.1

save_strategy: "steps"
save_steps: 2000
